# -*- coding: utf-8 -*-
"""london_air_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-Q6W45jZU9Lhj38Yq334z7XFU5IfIja

'''
London Air Quality Analysis 2023
=================================
Comprehensive analysis of hourly pollutant data across the full year.
Covers: descriptive stats, WHO compliance, monthly/seasonal/hourly trends,
AQI distribution, correlation analysis, and visualisations.
'''
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from pathlib import Path

FILE = "London_Air_Quality_Analysis_2023.xlsx"
OUT_DIR = Path("plots")
OUT_DIR.mkdir(exist_ok=True)

POLLUTANTS = ["CO (µg/m³)", "NO₂ (µg/m³)", "SO₂ (µg/m³)",
              "O₃ (µg/m³)", "PM2.5 (µg/m³)", "PM10 (µg/m³)"]

# WHO 2021 annual mean guidelines (µg/m³)
WHO_ANNUAL = {
    "CO (µg/m³)":    4000,   # 4 mg/m³ → µg
    "NO₂ (µg/m³)":  10,
    "SO₂ (µg/m³)":  40,
    "O₃ (µg/m³)":   60,
    "PM2.5 (µg/m³)": 5,
    "PM10 (µg/m³)": 15,
}

MONTH_ORDER = ["January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"]

SEASON_MAP = {
    "December": "Winter", "January": "Winter", "February": "Winter",
    "March": "Spring",  "April": "Spring",  "May": "Spring",
    "June": "Summer",   "July": "Summer",   "August": "Summer",
    "September": "Autumn", "October": "Autumn", "November": "Autumn",
}

AQI_BINS   = [0, 50, 100, 150, 200, 300, float("inf")]
AQI_LABELS = ["Good", "Moderate", "Unhealthy for Sensitive",
               "Unhealthy", "Very Unhealthy", "Hazardous"]

plt.rcParams.update({"figure.dpi": 130, "font.family": "sans-serif",
                     "axes.spines.top": False, "axes.spines.right": False})

# ── 1. Load & pre-process ─────────────────────────────────────────────────────
print("=" * 60)
print("1. LOADING DATA")
print("=" * 60)

df = pd.read_excel(FILE, sheet_name="Raw Data")
df["Date"]   = pd.to_datetime(df["Date"])
df["Hour"]   = pd.to_datetime(df["Hour"], format="%H:%M:%S").dt.hour
df["Month"]  = pd.Categorical(df["Month"], categories=MONTH_ORDER, ordered=True)
df["Season"] = df["Month"].map(SEASON_MAP)
df["DayOfWeek"] = df["Date"].dt.day_name()
df["WeekType"]  = df["Date"].dt.dayofweek.apply(
    lambda x: "Weekend" if x >= 5 else "Weekday"
)

print(f"Records : {len(df):,}")
print(f"Period  : {df['Date'].min().date()} → {df['Date'].max().date()}")
print(f"Nulls   : {df[POLLUTANTS + ['AQI']].isnull().sum().sum()}")

print("\n" + "=" * 60)
print("2. DESCRIPTIVE STATISTICS")
print("=" * 60)

stats = df[POLLUTANTS + ["AQI"]].describe().T
stats["cv_%"] = (stats["std"] / stats["mean"] * 100).round(1)
print(stats.round(3).to_string())

# ── 3. WHO compliance ─────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("3. WHO ANNUAL GUIDELINE COMPLIANCE")
print("=" * 60)

annual_means = df[POLLUTANTS].mean()
who_df = pd.DataFrame({
    "Annual Mean": annual_means,
    "WHO Guideline": pd.Series(WHO_ANNUAL),
}).round(2)
who_df["Exceedance Factor"] = (who_df["Annual Mean"] / who_df["WHO Guideline"]).round(2)
who_df["Status"] = who_df["Exceedance Factor"].apply(
    lambda x: "✅ Compliant" if x <= 1 else f"❌ Exceeds {x:.1f}"
)
print(who_df.to_string())

print("\n" + "=" * 60)
print("4. MONTHLY AVERAGES")
print("=" * 60)

monthly = df.groupby("Month", observed=True)[POLLUTANTS + ["AQI"]].mean().round(2)
print(monthly.to_string())

# Identify peak month per pollutant
peak_months = monthly[POLLUTANTS].idxmax()
print("\nPeak month per pollutant:")
print(peak_months.to_string())

print("\n" + "=" * 60)
print("5. SEASONAL AVERAGES")
print("=" * 60)

seasonal = df.groupby("Season", observed=True)[POLLUTANTS + ["AQI"]].mean().round(2)
seasonal = seasonal.loc[["Winter", "Spring", "Summer", "Autumn"]]
print(seasonal.to_string())

print("\n" + "=" * 60)
print("6. HOURLY PATTERNS")
print("=" * 60)

hourly = df.groupby("Hour")[POLLUTANTS + ["AQI"]].mean().round(2)
rush_hours = [7, 8, 9, 17, 18, 19]
print("Rush-hour averages (7-9 & 17-19):")
print(hourly.loc[rush_hours].round(2).to_string())
print(f"\nPeak AQI hour : {hourly['AQI'].idxmax():02d}:00"
      f" ({hourly['AQI'].max():.2f})")
print(f"Lowest AQI hour: {hourly['AQI'].idxmin():02d}:00"
      f" ({hourly['AQI'].min():.2f})")

print("\n" + "=" * 60)
print("7. WEEKDAY vs WEEKEND")
print("=" * 60)

wk = df.groupby("WeekType")[POLLUTANTS + ["AQI"]].mean().round(2)
print(wk.to_string())
diff_pct = ((wk.loc["Weekend"] - wk.loc["Weekday"]) /
            wk.loc["Weekday"] * 100).round(1)
print("\nWeekend vs Weekday % difference:")
print(diff_pct.to_string())

print("\n" + "=" * 60)
print("8. AQI DISTRIBUTION")
print("=" * 60)

df["AQI_Category"] = pd.cut(df["AQI"], bins=AQI_BINS, labels=AQI_LABELS)
aqi_dist = df["AQI_Category"].value_counts().sort_index()
aqi_pct  = (aqi_dist / len(df) * 100).round(2)
aqi_summary = pd.DataFrame({"Hours": aqi_dist, "Pct %": aqi_pct})
print(aqi_summary.to_string())

daily_aqi = df.groupby("Date")["AQI"].mean().sort_values(ascending=False)
print("\nTop-10 worst daily AQI:")
print(daily_aqi.head(10).round(2).to_string())

print("\n" + "=" * 60)
print("9. PEARSON CORRELATION MATRIX")
print("=" * 60)

corr = df[POLLUTANTS + ["AQI"]].corr().round(3)
print(corr.to_string())

corr_pairs = (corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
              .stack()
              .sort_values(key=abs, ascending=False))
print("\nTop-5 strongest correlations:")
print(corr_pairs.head(5).round(3).to_string())

print("\n" + "=" * 60)
print("10. OUTLIER SUMMARY (IQR ×1.5)")
print("=" * 60)

for col in POLLUTANTS:
    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    outliers = df[(df[col] < q1 - 1.5 * iqr) | (df[col] > q3 + 1.5 * iqr)]
    pct = len(outliers) / len(df) * 100
    print(f"  {col:<20} outliers: {len(outliers):>5} ({pct:.1f}%)")

print("\n" + "=" * 60)
print("11. GENERATING PLOTS")
print("=" * 60)

# --- Fig 1: Monthly AQI trend ---
fig, ax = plt.subplots(figsize=(11, 4))
monthly_aqi = df.groupby("Month", observed=True)["AQI"].mean()
ax.plot(monthly_aqi.index.astype(str), monthly_aqi.values,
        marker="o", linewidth=2, color="#E84040")
ax.fill_between(range(len(monthly_aqi)), monthly_aqi.values, alpha=0.15, color="#E84040")
ax.set_title("Monthly Average AQI — London 2023", fontsize=13, fontweight="bold")
ax.set_xlabel("Month"); ax.set_ylabel("AQI")
ax.tick_params(axis="x", rotation=45)
plt.tight_layout()
print("monthly_aqi")

# --- Fig 2: Hourly AQI heatmap (hour × month) ---
pivot = df.pivot_table(values="AQI", index="Hour", columns="Month",
                       aggfunc="mean", observed=True)
fig, ax = plt.subplots(figsize=(13, 6))
sns.heatmap(pivot, cmap="YlOrRd", ax=ax, linewidths=0.3,
            cbar_kws={"label": "AQI"})
ax.set_title("AQI by Hour × Month — London 2023", fontsize=13, fontweight="bold")
ax.set_xlabel("Month"); ax.set_ylabel("Hour of Day")
plt.tight_layout()
print("aqi_heatmap")

# --- Fig 3: Seasonal pollutant bar chart ---
season_order = ["Winter", "Spring", "Summer", "Autumn"]
sel_pollutants = ["NO₂ (µg/m³)", "O₃ (µg/m³)", "PM2.5 (µg/m³)", "PM10 (µg/m³)"]
seasonal_sel = df.groupby("Season")[sel_pollutants].mean().loc[season_order]
fig, axes = plt.subplots(1, 4, figsize=(14, 4), sharey=False)
colours = ["#4E79A7", "#F28E2B", "#E15759", "#76B7B2"]
for ax, col, c in zip(axes, sel_pollutants, colours):
    ax.bar(season_order, seasonal_sel[col], color=c, alpha=0.85)
    ax.set_title(col.split(" (")[0], fontsize=10)
    ax.set_ylabel("µg/m³")
    ax.tick_params(axis="x", rotation=30)
fig.suptitle("Seasonal Pollutant Averages — London 2023",
             fontsize=12, fontweight="bold")
plt.tight_layout()
print("seasonal_bars")

# --- Fig 4: Correlation heatmap ---
fig, ax = plt.subplots(figsize=(8, 6))
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap="coolwarm",
            center=0, ax=ax, linewidths=0.5,
            cbar_kws={"shrink": 0.8})
ax.set_title("Pearson Correlation Matrix — Pollutants & AQI",
             fontsize=12, fontweight="bold")
plt.tight_layout()
print("correlation")

# --- Fig 5: AQI category distribution pie ---
fig, ax = plt.subplots(figsize=(7, 5))
colours_pie = ["#2ECC71", "#F1C40F", "#E67E22", "#E74C3C", "#8E44AD", "#2C3E50"]
wedge_data  = aqi_dist[aqi_dist > 0]
wedge_cols  = [colours_pie[i] for i, v in enumerate(aqi_dist) if v > 0]
ax.pie(wedge_data, labels=wedge_data.index, colors=wedge_cols,
       autopct="%1.1f%%", startangle=140, pctdistance=0.82)
ax.set_title("AQI Category Distribution — London 2023",
             fontsize=12, fontweight="bold")
plt.tight_layout()
print("aqi_pie.png")

# --- Fig 6: Daily AQI rolling average ---
daily_ts = df.groupby("Date")["AQI"].mean()
fig, ax = plt.subplots(figsize=(12, 4))
ax.plot(daily_ts.index, daily_ts.values, alpha=0.35, color="#999", linewidth=0.8)
ax.plot(daily_ts.index, daily_ts.rolling(14).mean(), color="#E84040",
        linewidth=2, label="14-day rolling mean")
ax.set_title("Daily AQI with 14-Day Rolling Mean — London 2023",
             fontsize=13, fontweight="bold")
ax.set_xlabel("Date"); ax.set_ylabel("AQI")
ax.legend()
plt.tight_layout()
print("daily_aqi_rolling")

# --- Fig 7: Weekday vs Weekend hourly AQI ---
hourly_wk = df.groupby(["Hour", "WeekType"])["AQI"].mean().unstack()
fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(hourly_wk.index, hourly_wk["Weekday"], label="Weekday",
        color="#4E79A7", linewidth=2)
ax.plot(hourly_wk.index, hourly_wk["Weekend"], label="Weekend",
        color="#F28E2B", linewidth=2, linestyle="--")
ax.set_title("Hourly AQI: Weekday vs Weekend — London 2023",
             fontsize=12, fontweight="bold")
ax.set_xlabel("Hour of Day"); ax.set_ylabel("AQI")
ax.xaxis.set_major_locator(mticker.MultipleLocator(2))
ax.legend()
plt.tight_layout()
print("weekday_weekend_aqi")
plt.show()

print("\n" + "=" * 60)
print("12. KEY FINDINGS SUMMARY")
print("=" * 60)

worst_pollutant = who_df[who_df["Exceedance Factor"] > 1]["Exceedance Factor"].idxmax()
print(f"  Worst WHO exceedance : {worst_pollutant} "
      f"(×{who_df.loc[worst_pollutant, 'Exceedance Factor']:.1f})")
print(f"  Highest AQI month   : {monthly['AQI'].idxmax()} "
      f"({monthly['AQI'].max():.2f})")
print(f"  Cleanest month      : {monthly['AQI'].idxmin()} "
      f"({monthly['AQI'].min():.2f})")
print(f"  Peak AQI season     : {seasonal['AQI'].idxmax()} "
      f"({seasonal['AQI'].max():.2f})")
print(f"  Worst single day    : {daily_aqi.index[0].date()} "
      f"(AQI {daily_aqi.iloc[0]:.2f})")
good_pct = aqi_pct.get("Good", 0)
print(f"  Hours in 'Good' AQI : {good_pct:.1f}%")
print(f"\nAll plots saved to → {OUT_DIR.resolve()}/")